### ISSUE TITLE
go get github.com/shotdog/scheduler 时候错误

### ISSUE THREAD

**Issue by xwinie** [shotdog/scheduler#1]
C:\Users\winie>go get github.com/shotdog/scheduler

package scheduler/controller: unrecognized import path "scheduler/controller" (import path does not begin with hostname)
package scheduler/entity: unrecognized import path "scheduler/entity" (import path does not begin with hostname)
package scheduler/job: unrecognized import path "scheduler/job" (import path does not begin with hostname)

**Comment by shotdog** [comment]
do you install the git client

**Comment by shotdog** [comment]
close
