### ISSUE TITLE
go get github.com/shotdog/scheduler fail

### ISSUE THREAD

**Issue by zzs258** [shotdog/scheduler#2]
package scheduler/controller: unrecognized import path "scheduler/controller" (import path does not begin with hostname)
package scheduler/entity: unrecognized import path "scheduler/entity" (import path does not begin with hostname)
package scheduler/job: unrecognized import path "scheduler/job" (import path does not begin with hostname)

**Comment by shotdog** [comment]
change the package   begin  with hostname such as **github.com/shotdog/scheduler/entity**

**Comment by zzs258** [comment]
您能再说详细点吗 ，没有太明白什么意思

**Comment by zzs258** [comment]
里面的引入路径能改一下，而且您 包的安装顺序 ，期望您能改变一下

**Comment by shotdog** [comment]
@zzs258 OK

**Comment by shotdog** [comment]
close
