### ISSUE TITLE
任务依赖

### ISSUE THREAD

**Issue by lrgoodboy** [shotdog/scheduler#3]
请问任务依赖有考虑吗，是如何解决的？

**Comment by shotdog** [comment]
@lrgoodboy 
任务依赖？ 你所说的比如：任务B下载任务依赖任务A的生成文件的任务？如果任务A没有完成，那么任务B 想等待任务A完成后执行？这类场景的依赖？ 不知道我举例是否你所说的任务依赖？

定时任务job有两点做到:各个不能够依赖和保持幂等操作无论执行多少次不影响结果。

**Comment by lrgoodboy** [comment]
@shotdog 就是你说的那样，
要做到的是前置任务执行失败，后置任务不再执行，并且通知失败就可以了

**Comment by shotdog** [comment]
finish  close !
